[package]
name = "namus-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
futures = "0.3.31"
log = "0.4.22"
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1.41", features = ["full"] }
