[package]
name = "namus-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
log = "0.4.22"
reqwest = { version = "0.12", features = ["json"] }
serde_derive = "1.0.215"
serde_json = "1.0"
tokio = { version = "1.41", features = ["full"] }
url = "2.5.3"
